"""create file recovery

Revision ID: 1b0e8b24bb0c
Revises: 7a8b302f7036
Create Date: 2024-10-25 17:22:30.498952

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b0e8b24bb0c"
down_revision: Union[str, None] = "7a8b302f7036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_recoveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "QUEUED",
                "PENDING",
                name="recoverystatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "recovery_method",
            sa.Enum(
                "SHADOW_COPY",
                "BACKUP_RESTORE",
                "FILE_HISTORY",
                "CLOUD_BACKUP",
                "LOCAL_BACKUP",
                "REMOTE_RECOVERY",
                "MANUAL",
                "DEFAULT",
                name="recoverymethod",
            ),
            nullable=False,
        ),
        sa.Column("file_size", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_file_recoveries_id"), "file_recoveries", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_recoveries_id"), table_name="file_recoveries")
    op.drop_table("file_recoveries")
    # ### end Alembic commands ###
