"""create activity logs

Revision ID: 7a8b302f7036
Revises: de7ad0212861
Create Date: 2024-10-22 12:24:31.411885

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a8b302f7036"
down_revision: Union[str, None] = "de7ad0212861"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_activity_type"),
        "activity_logs",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_created_at"),
        "activity_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_device_id"), "activity_logs", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_org_id"), "activity_logs", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_severity"), "activity_logs", ["severity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_logs_severity"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_org_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_device_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_created_at"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_activity_type"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
