"""Create Inventory

Revision ID: b54a93e81893
Revises: 1ec335553267
Create Date: 2024-09-22 13:00:40.576322

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b54a93e81893"
down_revision: Union[str, None] = "1ec335553267"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("hash", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "DENIED", name="approvalstatus"),
            nullable=True,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=True),
        sa.Column("is_global", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_name"), "applications", ["name"], unique=False
    )
    op.create_table(
        "inventories",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("application_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "DENIED", name="approvalstatus"),
            nullable=True,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventories")
    op.drop_index(op.f("ix_applications_name"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
