"""Add org_id in file recovery table

Revision ID: bf71a03ba27e
Revises: 1b0e8b24bb0c
Create Date: 2024-11-19 20:06:27.287381

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf71a03ba27e"
down_revision: Union[str, None] = "1b0e8b24bb0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum type first
    op.execute(
        "CREATE TYPE severitylevel AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity_logs",
        "severity",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="severitylevel"),
        existing_nullable=False,
        postgresql_using="severity::severitylevel",
    )
    op.add_column("file_recoveries", sa.Column("org_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_recoveries", "org_id")
    op.alter_column(
        "activity_logs",
        "severity",
        existing_type=sa.Enum(
            "CRITICAL", "HIGH", "MEDIUM", "LOW", name="severitylevel"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.execute("DROP TYPE severitylevel")

    # ### end Alembic commands ###
