"""remove path and is_global

Revision ID: de7ad0212861
Revises: b54a93e81893
Create Date: 2024-10-09 14:07:42.354760

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de7ad0212861"
down_revision: Union[str, None] = "b54a93e81893"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "is_global")
    op.drop_column("applications", "path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "applications",
        sa.Column("is_global", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
