#!/usr/bin/env sh

#
#
echo NEXT_PUBLIC_KEYCLOAK_URL=$NEXT_PUBLIC_KEYCLOAK_URL > .env
echo NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=$NEXT_PUBLIC_KEYCLOAK_CLIENT_ID >> .env
echo NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL >> .env
echo NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL >> .env
echo NEXT_PUBLIC_APP_REALM=$NEXT_PUBLIC_APP_REALM >> .env
echo NEXT_PUBLIC_AGENT_BINARY_API_URL=$NEXT_PUBLIC_AGENT_BINARY_API_URL >> .env
echo NEXT_PUBLIC_CONSOLE_API_URL=$NEXT_PUBLIC_CONSOLE_API_URL >> .env