version: "3.9"

x-cnf: &cnf
  networks:
    - memcrypt_app
  logging:
    driver: "json-file"
    options:
      max-size: "200k"

networks:
  memcrypt_app:

services:
  memcrypt_console:
    build: .
    container_name: memcrypt_console
    hostname: memcrypt_console
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - CONSOLE_DATABASE_URL=${CONSOLE_DATABASE_URL}
    <<: *cnf
