[tool.poetry]
name = "console"
version = "0.1.0"
description = ""
authors = ["Dawood Mohammed <dawood.mohammed@appnetwise.com>"]
readme = "README.md"
packages = [{include = "app", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
sqlalchemy = "^2.0.34"
psycopg2-binary = "^2.9.9"
alembic = "^1.13.2"
python-dotenv = "^1.0.1"
uvicorn = "^0.32.0"
pydantic-settings = "^2.5.2"
pytest = "^8.3.2"
requests = "^2.32.3"
python-jose = "^3.3.0"
passlib = "^1.7.4"
python-keycloak = "^4.4.0"
contextvars = "^2.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
httpx = "^0.27.2"
pytest-cov = "^5.0.0"
black = "^24.8.0"
flake8 = "^7.1.1"
mypy = "^1.11.2"
fastapi = "^0.115.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
pythonpath = "src"

[tool.poetry.scripts]
db_upgrade = "alembic:main upgrade head"
db_downgrade = "alembic:main downgrade -1"
db_revision = "alembic:main revision --autogenerate"
