name: E2E_Tests

on:
  push:
    branches: ["quality-assurance"]
    paths:
      - "tests/e2e/**"
  workflow_dispatch:
    inputs:
      ENVIRONMENT_ID:
        type: choice
        description: e2e test environment id
        default: 
        options: 
          - qa
          - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 60
    defaults:
      run:
        working-directory: tests/e2e
    steps:
      - uses: actions/checkout@v4

      - name: Set default value
        id: env_id
        run: |
          environment_id=${{ github.event.inputs.ENVIRONMENT_ID }}
          echo "::set-output name=environment::${environment_id:-"qa"}"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xserver-xorg-core \
            xserver-xorg-video-vmware \
            xvfb \
            x11-xserver-utils \
            maven

      - name: Start Xvfb and Set DISPLAY
        run: |
          Xvfb :99 &              
          sleep 3                 
          export DISPLAY=:99      
          echo "DISPLAY set to $DISPLAY" 
          xhost +                 
        env:
          DISPLAY: ":99"

      # - name: Install Maven
      #   run: sudo apt-get install -y maven

      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Ensure browsers are installed
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chrome"   #"install --with-deps"

      - name: Run E2E Tests
        shell: bash
        continue-on-error: true
        run: |
          echo "Running tests with DISPLAY=$DISPLAY"
          ls
          rm -rf reports
          echo "Deleted reports folder"
          mvn test -DsuiteXmlFile=RegressionTestSuite.xml -Dplaywright.headless=true -Denv=${{ steps.env_id.outputs.environment }}
        env:
          DISPLAY: ":99" 

      - name: Move reports
        shell: bash
        run: |
          #!/bin/bash

          SOURCE_DIR="./reports"   
          DEST_DIR="./results"
          mkdir $DEST_DIR
          ls -td "$SOURCE_DIR"/*
          LATEST_REPORT_DIR=$(ls -td "$SOURCE_DIR"/* | head -n 1)
          echo "Latest folder found: $LATEST_REPORT_DIR"
          if [ -z "$LATEST_REPORT_DIR" ]; then
              echo "No report directory found."
              exit 1
          fi
          echo "Moving reports from: $LATEST_REPORT_DIR"
          mv "$LATEST_REPORT_DIR"/* "$DEST_DIR"/
          mv "$DEST_DIR"/Index.html "$DEST_DIR"/index.html
          rmdir "$LATEST_REPORT_DIR"
          echo "Reports moved to: $DEST_DIR"


      - name: Upload Test Results
        if: always()
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report
          path: tests/e2e/results

  upload_report:
    needs: e2e
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Upload E2E Report to gh-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download E2E report artifact
        uses: actions/download-artifact@v4
        with:
          name: e2e-report
          path: e2e-report

      - name: Push reports to gh-pages branch
        run: |
          today=$(date +'%d%m%Y')
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git checkout gh-pages
          git pull origin gh-pages
          if [ -d "e2e/$today" ]; then
            rm -rf "e2e/$today"
            echo "Directory 'e2e/$today' removed."
          else
            echo "Directory 'e2e/$today' does not exist."
          fi
          mkdir -p "e2e/$today"
          cp -r e2e-report/* "e2e/$today/"
          bash get_folders.sh
          git add index.html e2e/
          git commit -m "[skip ci] Added E2E report for $today" || echo "No changes to commit"
          git push origin gh-pages
